_target_: demo_generation.demogen.DemoGen

data_root: data
source_name: 0219-cube

task_n_object: 1

use_linear_interpolation: false
interpolate_step_size: 0.01

use_manual_parsing_frames: true
parsing_frames:
  motion-1: 0
  skill-1: 17
  motion-2: null
  skill-2: null

mask_names:
  object: green cube

trans_range:
  src:
    object: [[0, 0, 0], [0, 0, 0]]
    target: null
  test:
    object: [[-0.15, -0.15, 0], [0.15, 0.15, 0]]
    target: null

generation:
  range_name: test
  n_gen_per_source: 16
  render_video: True
  mode: grid
